server:
  port: 8088

app:
  api-prefix: /api

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id : user-service
          uri: http://localhost:8080/
          predicates:
          - Path=${app.api-prefix}/user-service/user/**, ${app.api-prefix}/user-service/permissions/**, ${app.api-prefix}/user-service/role/**
          filters:
          - StripPrefix=1
        - id: security-service
          uri: http://localhost:8081/
          predicates:
          - Path=${app.api-prefix}/security-service/auth/**
          filters:
          - StripPrefix=1
  main:
    allow-circular-references: true
