server:
  port: 8085
  servlet:
    context-path: "/quiz-service"
spring:
  application:
    name: quiz-service
  datasource:
    url: jdbc:mysql://localhost:3306/reading-quiz-service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  main:
    allow-circular-references: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/