server:
  port: 9000
  servlet:
    context-path: /admin-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: admin-service

app:
  admin:
    services:
      user-service:
        name: user-service
        context-path: /user-service
      collection-service:
        name: collection-service
        context-path: /collection-service
      word-service:
        name: word-service
        context-path: /word-service
      quiz-service:
        name: quiz-service
        context-path: /quiz-service