server:
  port: 9000
  servlet:
    context-path: /admin-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  security:
    user:
      name: client
      password: client
  boot:
    admin:
      client:
        instance:
          metadata:
            user.name: ximuoimo88
            user.password: ximuoimo88