
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  application:
    name: eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF