
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enable-self-preservation: true #Ensuring life of Services when instance lost internet,...
    renewal-threshold-update-interval-ms: 60000
#  instance:
#    prefer-ip-address: true #get ip instead of localhost

spring:
  application:
    name: eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF