server:
  port: 8080
  servlet:
    context-path: "/user-service"


spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user-service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification2-group
      auto-offset-reset: earliest
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 172306803667-nd4bhi0v342ufdsev3v33116nkh287ar.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope:
              - email
              - profile
              - email
              - address
              - phone
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo


app:
  services:
    security-service:
      name: security-service
      context-path: /security-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
