server:
  port: 8081
  servlet:
    context-path: "/security-service"


spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mysql://localhost:3306/security-service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    generate-ddl: true
    show-sql: true


jwt:
  keyset: engappmicroservicebytrancaonguyen1011882602@@
  signerkey: a37ae2355c54a5a5717c6951f97ef808829e6915293c4647d85e76f76890dc1e522a976484064dbdcf2110890e7f3f1c
  valid-duration: 60
  refreshable-duration: 60

app:
  services:
    user-service:
      name: user-service
      context-path: /user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
