server:
  port: 8086
  servlet:
    context-path: "/reading-quiz-service"
spring:
  application:
    name: reading-quiz-service
  datasource:
    url: jdbc:mysql://localhost:3306/reading-quiz-service
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/