server:
  port: 8085
  servlet:
    context-path: "/reading-quiz-service"
spring:
  application:
    name: reading-quiz-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/reading-quiz-service?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/